export const INDUSTRIES = [
  'Software',
  'Trading',
  'Agriculture',
  'Apparel',
  'Automotive',
  'Banking',
  'Chemicals',
  'Construction',
  'Consulting',
  'Education',
  'Electronics',
  'Energy',
  'Engineering',
  'Entertainment',
  'Finance',
  'Food',
  'Government',
  'Healthcare',
  'Hospitality',
  'Insurance',
  'Legal',
  'Logistics',
  'Manufacturing',
  'Media',
  'Mining',
  'Nonprofit',
  'Pharmaceuticals',
  'Professional services',
  'Real estate',
  'Retail',
  'Shipping',
  'Telecommunications',
  'Textiles',
  'Transportation',
  'Travel',
  'Utilities',
  'Wholesale',
  'Advertising',
  'Aerospace',
  'Biotech',
  'Consumer goods',
  'E-commerce',
  'Facilities',
  'HR services',
  'IT services',
  'Marketing',
  'Oil and gas',
  'Publishing',
  'Security',
  'Sports',
  'Staffing',
  'Waste management',
] as const;

export type Industry = (typeof INDUSTRIES)[number];

export const isIndustry = (value: string): value is Industry =>
  (INDUSTRIES as readonly string[]).includes(value);
