http:
  routers:
    api:
      rule: "PathPrefix(`/health`) || PathPrefix(`/ready`) || PathPrefix(`/v1`)"
      service: api
      entryPoints:
        - web
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"
